codewithnick/ascii-art

- Fonts/Boomer/boomer.h
- example.cpp
> added coded for Boomer Font Letter Q

- Fonts/Boomer/boomer.h
- example.cpp
> added U in font boomer

- Fonts/Boomer/boomer.h
> added letter C of boomer

- Fonts/Boomer/boomer.h
> Added Letter E in Boomer font

- Fonts/Boomer/boomer.h
- example.cpp
> Boomer Letter b

- Fonts/Boomer/boomer.h
- example.cpp
can add this for boomer font X
> I wrote code for Boomer font X

- Fonts/Boomer/boomer.h
Modified boomer.h
I have written code for Letter F in Boomer font.
Sample Output:
#17 
closes #17
> Added Letter F in Boomer Font

- Fonts/Boomer/boomer.h
- example.cpp
Reverts codewithnick/ascii-art#103
> Revert "Number Eight to Boomer Font"

- Fonts/Boomer/boomer.h
- example.cpp
added code for character '4' in Boomer font
> vikash Burman -> 4 boomer

- Fonts/Boomer/boomer.h
Written Code for Letter g in Boomer font.
#96 
closes #96
> Code written for Letter g in boomer font

- Fonts/Boomer/boomer.h
- example.cpp
> f added in boomer

- Fonts/Boomer/boomer.h
Written code for letter j in boomer font
#97 
#97
> Added letter j in boomer font

- Fonts/Straight/straight.h
- Fonts/starwar/starwar.h
- example.cpp
Added B(capital) letter in straight.h
closes #30 
closes #31
> added B letter in straight.h

- Fonts/Boomer/boomer.h
Resolved the code for Boomer : v
issue#71
> Wrote a code for Boomer : v *RESOLVED

- Fonts/Boomer/boomer.h
> Rajat - nine added in boomer

- Fonts/Straight/straight.h
Created "R,V,i" in straight font
> Created "R,V,i" in straight font

- Fonts/Straight/straight.h
Abhishek - added S, T, x in straight
> Abhishek - added S, T, x in straight

- Fonts/Boomer/boomer.h
> Added 'z' in boomer font

- Fonts/banner/banner.h
> added character 8 to banner font

- Fonts/banner/banner.h
> Added F in banner font

- Fonts/Straight/straight.h
> Added letter I in straight.h

- Fonts/starwar/starwar.h
> added H to starwar

- Fonts/starwar/starwar.h
Added letter C in starwar.h
closes #37
> Added letter C in starwar.h

- Fonts/Straight/straight.h
> Added letter 'W' in straight.h

- Fonts/banner/banner.h
Added the code of uppercase alphabet T for the banner font.
Closes issue #162
> Added character T to banner font

- Fonts/banner/banner.h
I have added the font 'H' and 'M' to banner.h   #193  #191 
closes #191 
closes #193
> Alucard017

- Fonts/carlos/carlos.h
> Added letter C in carlos font

- Fonts/Straight/straight.h
- example.cpp
Added letter v in straight.h
closes #146
> Added letter v in straight.h

- Fonts/carlos/carlos.h
- example.cpp
Added Code For --- Font Carlos  Letter H
#213
closes #213
> Added Code for Carlos H

- Fonts/Boomer/boomer.h
> Added L in boomer

- Fonts/Boomer/boomer.h
- example.cpp
added letter t : BOOMER
closes #63
> added  letter t

- Fonts/banner/banner.h
Added the code for character 1 for the banner font
Closes issue #163
> Added character 1 to banner font

- Fonts/carlos/carlos.h
> sachin- D in carlos

- Fonts/carlos/carlos.h
Added 'E' and 'G' in the font Carlos
> vny- E,G in carlos

- Fonts/banner/banner.h
> Added character 4 to banner font

- Fonts/starwar/starwar.h
- example.cpp
I added code for starwar font : I
closes #222
> added <starwar> I

- Fonts/banner/banner.h
- example.cpp
I have written the code for letter G of banner font 
closes #236
> Banner font letter G

- Fonts/Boomer/boomer.h
- example.cpp
> Added letter 'n'

- Fonts/Straight/straight.h
> Added U in straight font

- Fonts/starwar/starwar.h
- example.cpp
I have added letter 'L' of the starwar font
closes #231
closes #249
> Letter L added

- Fonts/banner/banner.h
Added character: E to font: banner
closes #237
> added character:<E> to font: <banner>

- Fonts/carlos/carlos.h
> Q in carlos

- Fonts/starwar/starwar.h
- example.cpp
*I've added letter N of starwar*
closes #256
> Letter N added to font : starwar

- Fonts/banner/banner.h
- example.cpp
> Added O character

- Fonts/starwar/starwar.h
- example.cpp
*I have added letter X of the font starwar*
closes #254
> Letter X added to starwar

- Fonts/Straight/straight.h
- example.cpp
> added L in straight

- Fonts/Straight/straight.h
- Fonts/carlos/carlos.h
- example.cpp
> code for X of carlos font added

- Fonts/carlos/carlos.h
> added number char <0> in carlos.h

- Fonts/carlos/carlos.h
- example.cpp
> Added Z in carlos

- .github/workflows/main.yml
- readme.md
Added action to automatically update `readme.md` with the recent contributors. The action runs on every push to the `main` branch
> Automatic Readme update for contributor list.

- Fonts/starwar/starwar.h
- example.cpp
*I have added letter J to the font starwar*
closes #276
> Letter J added to font starwar

- Fonts/Straight/straight.h
- example.cpp
- readme.md
> Added H letter in the straight font

- Fonts/Boomer/boomer.h
- example.cpp
- readme.md
Added boomer letter h. closes #66 boomer letter h.
> Added boomer letter h.

- Fonts/starwar/starwar.h
- example.cpp
- readme.md
*I have added letter U to the font starwar*
closes #277
> Letter U added to font starwar

- Fonts/Straight/straight.h
- example.cpp
- readme.md
*Code for w of straight font is added*
closes #260 
closes #261
> Code for w of straight font is added

- Fonts/banner/banner.h
> added char<I> in banner

- Fonts/Straight/straight.h
> Added E in straight

- Fonts/starwar/starwar.h
- example.cpp
- readme.md
I have added letter M to the font starwar
closes #285
> Letter M added to font starwar

- Fonts/Straight/straight.h
- example.cpp
> character N of straight is add

- Fonts/Straight/straight.h
- example.cpp
> Add z/straight

- Fonts/Straight/straight.h
- example.cpp
Hey, i am new to opensource I have add F character in Straight font. If there is any issue plz Let me know.i am ready to contribute
closes #258
> Added 'F' character in straight.h

- Fonts/starwar/starwar.h
- example.cpp
- readme.md
*I have added letter P to the font starwar*
closes #303
closes #293
> Letter P added to the font starwar

- Fonts/Straight/straight.h
> Added 1 in straight

- Fonts/banner/banner.h
Added
Character : J
Font : banner
closes #315
> Add character: J to font: banner

- Fonts/banner/banner.h
Added
Character : N
Font : banner
closes #316
> Add character: N to font: banner

- Fonts/Straight/straight.h
- example.cpp
- readme.md
*Adding h of straight font*
closes #299
> Adding h of straight font

- Fonts/Straight/straight.h
- example.cpp
- readme.md
*Adding n of straight font*
closes #300
> Adding n of straight font

- Fonts/Straight/straight.h
- example.cpp
- readme.md
> Added character b in the straight font

- Fonts/carlos/carlos.h
> Added S in carlos

- Fonts/starwar/starwar.h
- example.cpp
Issue resolved
* Underscores changed to hyphens.
* thanks!
> Letter : T ; Font : Starwar 

- Fonts/starwar/starwar.h
- example.cpp
- readme.md
*I have added letter V to the font starwar*
closes #310
> Letter V added to the font starwar

- Fonts/Straight/straight.h
- example.cpp
- readme.md
> Added p character in straight font

- Fonts/Boomer/boomer.h
> Added number 0 to Boomer

- Fonts/starwar/starwar.h
Added character 0 to Starwar
closes #359
> Added character 0 to Starwar

- Fonts/Boomer/boomer.h
> Added number 2 to boomer

- Fonts/starwar/starwar.h
- example.cpp
- readme.md
*I've added letter D to the font starwar*
closes #311
> Letter D added to starwar

- Fonts/banner/banner.h
- readme.md
> added banner font P

- Fonts/starwar/starwar.h
- example.cpp
*I've added letter O to the font starwar*
closes #335
> Letter O added to starwar

- Fonts/Straight/straight.h
- example.cpp
- readme.md
> Letter t added in the font straight

- Fonts/Boomer/boomer.h
- example.cpp
> Added digit 6 to boomer

- Fonts/carlos/carlos.h
Character: 1
Font: carlos
closes #387
> Added 1 to carlos

- Fonts/starwar/starwar.h
- example.cpp
> Added digit 7 to starwar

- Fonts/Straight/straight.h
> Added M to Straight

- Fonts/starwar/starwar.h
- example.cpp
- readme.md
> Letter Y added to starwar

- Fonts/starwar/starwar.h
Added Character \<a> to font \<starwar>
Lowercase a isn't in the code, so I added the code for it (it's the same as uppercase A)
Even though the ascii art for both A's are the same, the input would be different for both, so this way the computer would read both no problem.
closes #417
> Added character <a> for <starwar>

- Fonts/starwar/starwar.h
Added \<G> to font \<starwar>
closes #412
> Added <G> to font <starwar>

- Fonts/Straight/straight.h
> Added O to Straight

- Fonts/starwar/starwar.h
- example.cpp
- readme.md
> Number 6 added to starwar

- Fonts/Boomer/boomer.h
- example.cpp
> Added letter l to boomer

- Fonts/Straight/straight.h
> added 9 to straight

- Fonts/Straight/straight.h
Hey, I have added the code so review and let me know any changes  needed
closes #424
> Added "2" Number to Straight

- Fonts/Straight/straight.h
> added six in straight

- Fonts/Straight/straight.h
> added 8 in straight

- Fonts/starwar/starwar.h
- example.cpp
- readme.md
> Letter Q added to starwar

- Fonts/carlos/carlos.h
> Added R to carlos

- Fonts/carlos/carlos.h
- example.cpp
> Added letter J to carlos

- Fonts/Straight/straight.h
> added 4 in straight

- Fonts/starwar/starwar.h
- example.cpp
> Number 3 added to starwar

- Fonts/starwar/starwar.h
- example.cpp
> Added letter K to starwar

- Fonts/Straight/straight.h
Added letter j to the font straight
closes #453
> Added letter j to font straight

- Fonts/carlos/carlos.h
- example.cpp
> Letter I added to font carlos

- Fonts/banner/banner.h
- example.cpp
- readme.md
> K in banner

- Fonts/banner/banner.h
Hey, i have add the code if any changes needed then let me know.
closes #462
> Added  Number '3'  to banner

- Fonts/banner/banner.h
- example.cpp
- readme.md
> i added in banner

- Fonts/carlos/carlos.h
- example.cpp
> Added letter K to carlos

- Fonts/Straight/straight.h
- readme.md
Filled matrix with proper symbols so that a 5 digit is generated.
> ASCII of 5 added 

- Fonts/Boomer/boomer.h
> Adjust boomer font to use dynamic character grid

- Fonts/Straight/straight.h
- readme.md
> added zero in straight

- Fonts/carlos/carlos.h
- example.cpp
- readme.md
> Letter N added to carlos

- Fonts/banner/banner.h
Added
Character : U
Font : banner
closes #317
> Add character: U to font: banner

- Fonts/banner/banner.h
- example.cpp
- readme.md
> j added in banner

- Ascii.h
- Fonts/starwar/starwar.h
- example.cpp
Add character: 'E' to font: 'starwar'
Fix minor case typo in example.cpp
closes #495
> Add character: E to font: starwar

- Fonts/carlos/carlos.h
- example.cpp
> Added Letter L to carlos

- Fonts/banner/banner.h
Added
Character : S
Font : banner
closes #168
> Add character: S to font: banner

- Fonts/Straight/straight.h
*Added D to the Straight font*
closes #511
> Added D to the Straight font

- Fonts/carlos/carlos.h
- example.cpp
- readme.md
> Letter M added to font carlos

- Fonts/block/block.h
> Added 1 to block

- Fonts/block/block.h
Character H added to the block font
closes #512
> Character H added to the block font

- Fonts/Straight/straight.h
Added \<G> to font \<straight>
closes #526
> Added <G> to font <straight>

- Fonts/carlos/carlos.h
- readme.md
Adding 9 in carlos 
issue:
closes #533
> adding 9 in carlos 

- Fonts/block/block.h
- example.cpp
> Letter R added to block

- Fonts/Straight/straight.h
> Adjust straight font to use dynamic character grid

- Fonts/carlos/carlos.h
- example.cpp
> Added Letter Y to carlos

- Fonts/block/block.h
- example.cpp
- readme.md
> Letter N added to block

- Fonts/block/block.h
> Added V to block

- Fonts/block/block.h
- Fonts/carlos/carlos.h
Added character 'T' to font 'Carlos'
[Issue #538 ](https://github.com/codewithnick/ascii-art/issues/538)
closes #538
> Added character: <T> to font: <CARLOS> #538

- Fonts/Straight/straight.h
- Fonts/carlos/carlos.h
> Added V in CARLOS

- Fonts/Straight/straight.h
> added X in Straight

- Fonts/banner/banner.h
- readme.md
Added V to banner font
resolved #549 issue
> Added V  to banner font

- Fonts/banner/banner.h
- readme.md
a is added to banner font
resolved #550 
> Added a to banner font

- Fonts/block/block.h
- readme.md
Added 5 & 9 char to Block-Font
> Vny- Added 5 & 9 char to Block-Font

- Fonts/block/block.h
- example.cpp
- readme.md
> Letter M added to block

- Fonts/carlos/carlos.h
> adding 8 in carlos

- Fonts/Straight/straight.h
- Fonts/fonts.h
- example.cpp
I have added the code letter P 
font : straight
thanks.
> Code added for letter P ; Font : straight

- Fonts/Straight/straight.h
Added 'X' to <straight>
closes #571
> [Fixes]: Added 'X' to <straight>

- Fonts/banner/banner.h
- Fonts/banner/banner.md
Adding character <v> to banner font 
Adding character <v> to banner font
#579
> Adding character <v> to banner font 

- Fonts/Boomer/boomer.h
- Fonts/banner/banner.h
- example.cpp
Added q to Boomer Font
closes #559
closes #593
> Added q to boomer Font

- Fonts/banner/banner.h
- readme.md
e is added in banner font
resolved #551
> Added e in banner font

- Fonts/Boomer/boomer.h
- readme.md
> Added letter 'm' font 'boomer'

- Fonts/Straight/straight.h
- readme.md
*Added character 's' in font straight*
closes #472
> Added charcter s in straight font 

- Fonts/block/block.h
Added character P and fixed a bug to the outer block of H
closes #606
> Added character P and fixed a bug to the outer block of H

- Fonts/block/block.h
added character E to font block
closes #605
> added character E to font block

- Fonts/banner/banner.h
> banner #559 ,5

- Fonts/block/block.h
- example.cpp
- readme.md
> docs(contributor): contrib-readme-action has updated readme

- Fonts/Straight/straight.h
>  z is added of straight

- Fonts/block/block.h
Character 7 added to block
closes #603
> Character 7 added to block

- Fonts/block/block.h
Character I added to block
closes #653
> Character I added to block

- Fonts/Boomer/boomer.h
- readme.md
> Added Code for Letter 3 Font Boomer

- Fonts/Straight/straight.h
- example.cpp
> added Y in straight

- Fonts/Straight/straight.h
> added character 'e' font 'straight'

- example.cpp
- readme.md
Character : z
Font : banner
closes #646
> Added character 'z' to font 'banner'

- Fonts/amongus/amongus.h
*Added letter B of type amongus font*
closes #708
> Added letter B of font amongus

- Fonts/block/block.h
- readme.md
> Added Code for Character B Font Block

- Fonts/banner/banner.h
- readme.md
increased the number of rows and columns and aligned it accordingly 
closesissue  #638
> lowercase q for banner font

- Fonts/amongus/amongus.h
Added letter 8 to font amongus
closes #723
> Added letter 8 to font amongus

- Fonts/banner/banner.h
- example.cpp
- readme.md
Character : x
Font : banner
closes #690
> Added character 'x' to font 'banner'

- Fonts/Straight/straight.h
- example.cpp
> added character 'd' font 'straight'

- Fonts/banner/banner.h
- example.cpp
*added l in banner*
closes #499
> added l in banner

- Fonts/carlos/carlos.h
- readme.md
> Added Code for Carlos U

- Fonts/drpepper/drpepper.h
added font H to drpepper
closes #670 
closes #672
> added H to drpepper

- Fonts/Straight/straight.h
> added character '5' to font 'straight'

- Fonts/drpepper/drpepper.h
Added font A to drpepper
added font A to drpepper
closes #662
> Added font A to drpepper

- Fonts/drpepper/drpepper.h
- readme.md
Drpepper T font added
closes #684
> Drpepper T

- Fonts/drpepper/drpepper.h
added letter S to drpepper
closes #687
> added letter S

- Fonts/amongus/amongus.h
Added to Ampongus font
closes #743
> added E to amongus font

- Fonts/Straight/straight.h
> added character 'a' font 'straight'

- Fonts/amongus/amongus.h
- example.cpp
Added character C of font amongus
closes #721
> Added Character "C" of font <amongus>

- Fonts/amongus/amongus.h
*Added <0> to amongus font*
closes #757
> Added <0> to amongus font

- Fonts/block/block.h
- readme.md
> Block.h : Letter 'Z' 

- Fonts/drpepper/drpepper.h
added font E to drpepper
closes #685
> added E to drpepper

- Fonts/amongus/amongus.h
added G to amongus font
closes #772
> added G to amongus font

- Fonts/banner/banner.h
- Fonts/carlos/carlos.md
- example.cpp
Add character 2 to banner
closes #716
> Add character 2 to banner

- Fonts/amongus/amongus.h
added F to amongus font
closes #753
> added F to amongus font

- Fonts/drpepper/drpepper.h
Added 'v' to drpepper
closes #750
> Added 'v' character to drpepper

- Fonts/drpepper/drpepper.h
Added font B to drpepper
closes #664
> Added B to drpepper

- Fonts/amongus/amongus.h
- example.cpp
Added the character D in the amongus font
closes #733
> Added character "D" to font: <amongus>

- Fonts/amongus/amongus.h
- readme.md
Added character 7 in font amongus
closes #693
> added character 7 in font amongus

- Fonts/drpepper/drpepper.h
> added code for b drpepper

- Fonts/drpepper/drpepper.h
>  added code drpepper a

- Fonts/amongus/amongus.h
Added new "S" character to font amongus
closes #722
> Add character: <S> to font: <amongus>

- Fonts/banner/banner.h
- example.cpp
>  added u in banner

- Fonts/drpepper/drpepper.h
Added font C to drpepper
closes #665
> Added C to drpepper

- Fonts/drpepper/drpepper.h
Added font D to drpepper
closes #666
> Added font D to drpepper

- Fonts/amongus/amongus.h
- example.cpp
character V added to font amongus
#715
> character V added to font amongus

- Fonts/block/block.h
- Fonts/block/block.md
- example.cpp
- readme.md
> 'G' (Block)

- Fonts/drpepper/drpepper.h
Added Q to drpepper
closes #689
> Added Q to drpepper

- Fonts/drpepper/drpepper.h
> added code i drpepper

- Fonts/drpepper/drpepper.h
Added R to drpepper
closes #688
> Added R to drpepper

- Fonts/amongus/amongus.h
- example.cpp
added K to amongus font
closes #776
> added K to amongus font

- Fonts/drpepper/drpepper.h
added I to drpepper
closes #672
> added I to drpepper

- Fonts/amongus/amongus.h
Added a to amongus font
closes #803
> Added a to amongus font

- Fonts/banner/banner.h
- readme.md
> added s in banner

- Fonts/drpepper/drpepper.h
- readme.md
drpepper n added aligning with baseline
closes #683
> drpepper n

- Fonts/amongus/amongus.h
added N to amongus font
closes #800
> added N to amongus font

- Fonts/block/block.h
Added <j> character to block font.
closes #809
> Added <j> to block font

- Fonts/drpepper/drpepper.h
> added code for drpepper 7

- Fonts/block/block.h
- example.cpp
- readme.md
> Added 'i' (Font Name - Block)

- Fonts/drpepper/drpepper.h
> added code for 8 drpepper

- Fonts/drpepper/drpepper.h
Added 3 to drpepper
closes #758
> Added 3 to drpepper

- Fonts/block/block.h
add C to block
closes #663 
closes #667 
closes #725
> add<C> to <block>

- Fonts/drpepper/drpepper.h
- readme.md
> drpepper M

- Fonts/amongus/amongus.h
added U to amongus font
closes #832
> added U to amongus font

- Fonts/block/block.h
- example.cpp
*Added character 4 to font block*
closes #695
> Added character 4 to font block

- Fonts/banner/banner.h
- readme.md
> added y in banner

- Fonts/drpepper/drpepper.h
added code 1 to drpepper
closes #700
> added code 1 to drpepper

- Fonts/drpepper/drpepper.h
> added code for 9 drpepper

- Fonts/drpepper/drpepper.h
Added 'u' to Drpepper
closes #764
> Added 'u' character to drpepper

- Fonts/amongus/amongus.h
- example.cpp
> added P in amongus

- Fonts/amongus/amongus.h
- example.cpp
Added 2 in amongus font
closes #834
> Added 2 in amongus font

- Fonts/block/block.h
- example.cpp
- readme.md
closes #854 
closes #851 
closes #544
> Added 'h' (Font-Block)

- Fonts/drpepper/drpepper.h
added K to drpepper
closes #675
> added K to drpepper

- Fonts/block/block.h
Added 2 to block font
closes #865
> Added 2 to block font

- Fonts/Straight/straight.h
- example.cpp
> added f in straight font

- readme.md
Added readme links to the main readme and added my profile to contributors list in readme
closes #836
> Updated readme with new fonts information

- Fonts/block/block.h
- example.cpp
Character F added to block
closes #620
> Character F added to block

- Fonts/banner/banner.h
- readme.md
> Added 0 in banner font

- Fonts/amongus/amongus.h
Added 3 in amongus font
closes #878
> Added 3 in amongus font

- Fonts/drpepper/drpepper.h
- example.cpp
character j added to drpepper
closes #876
> character j added to drpepper

- Fonts/amongus/amongus.h
- readme.md
Adding character 1 in font amongus
closes #692
> Adding character 1 in font amongus

- Fonts/drpepper/drpepper.h
- example.cpp
character h added to drpepper
closes #877
> character h added to drpepper

- Fonts/amongus/amongus.h
Contributed to ascii-art by adding a new character "Capital T" to the font amongus. Replicated the same design as shown in the amongus.md
closes #831
> Add character: <T> to font: <amongus>

- Fonts/starwar/starwar.h
Added W in starwar font
closes #893
> Added W in starwar font

- Fonts/starwar/starwar.h
Added Z in starwar font
closes #894
> Added Z in starwar font

- Fonts/drpepper/drpepper.h
- readme.md
> added x in drpeeper

- Fonts/amongus/amongus.h
> Added M in amongus

- Fonts/amongus/amongus.h
- example.cpp
> [Added] character 'x' in amongus

- Fonts/amongus/amongus.h
> [Added] character 'O' to font 'amongus'

- Fonts/amongus/amongus.h
- example.cpp
> [Added] chracter 'Q' to font 'amongus'

- Fonts/amongus/amongus.h
> [Added] character 'd' to font 'amongus'

- Fonts/carlos/carlos.h
Added O in carlos font
closes #920
> Added O in carlos font

- Fonts/carlos/carlos.h
- readme.md
>  adding 2 in carlos

- Fonts/block/block.h
added 3 in block font
closes #921
> added 3 in block font

- Fonts/drpepper/drpepper.h
> added Y in drpepper

- Fonts/drpepper/drpepper.h
> added W in drpepper

- Fonts/amongus/amongus.h
- example.cpp
- readme.md
> added character to amongus

- Fonts/amongus/amongus.h
- example.cpp
- readme.md
> added z to amongus

- Fonts/block/block.h
- example.cpp
- readme.md
> Added small c in block font

- Fonts/drpepper/drpepper.h
Added character <c> to font <drpepper>
closes #903
> Added character <c> to font <drpepper>

- Fonts/Straight/straight.h
- example.cpp
added 3 to straight
#452
closes #452
> added 3 to straight

- Fonts/drpepper/drpepper.h
> added Y again

- Fonts/block/block.h
*Added character 0  to font: block*
#935 
closes #935
> Added character 0  to font: block

- Fonts/drpepper/drpepper.h
added 2 in drpepper font
closes #945
> added 2 in drpepper font

- Fonts/block/block.h
- readme.md
> Added e in block font

- Fonts/banner/banner.h
added 6 in banner font
#Reference number #866
closes #866
> added 6 in banner font

- Fonts/amongus/amongus.h
Added character <W> to font <amongus> #904 
closes #904
> Added character <W> to font <amongus>

- Fonts/amongus/amongus.h
Added character <c> to font <amongus>
closes #905
> Added character <c> to font <amongus>

- Fonts/amongus/amongus.h
Added character <s> to font <amongus>
closes #906
> Added character <s> to font <amongus>

- Fonts/amongus/amongus.h
- readme.md
added j in amongus font
closes #940
> added j in amongus font

- Fonts/drpepper/drpepper.h
Add <0>to < drpepper >
closes #872
> Add <0>to <drpepper>

- Fonts/Straight/straight.h
- Fonts/carlos/carlos.h
> Added six in carlos

- Fonts/amongus/amongus.h
Added digit <5> to font <amongus>
closes #907
> Added digit <5> to font <amongus>

- Fonts/drpepper/drpepper.h
- example.cpp
added s in font drpepper
closes #987
> added s in font drpepper

- Fonts/drpepper/drpepper.h
- example.cpp
- readme.md
> Added letter d to Drpepper

- Fonts/amongus/amongus.h
added k in amongus font
closes #942
> added k in amongus font

- Fonts/amongus/amongus.h
added R in amongus font
closes #930
> added R in amongus font

- Fonts/banner/banner.h
> Added h to banner

- Fonts/amongus/amongus.h
added l in amongus font
closes #943
> added l in amongus font

- Fonts/amongus/amongus.h
added e in amongus font
closes #931
> added e in amongus font

- Fonts/amongus/amongus.h
- readme.md
added m in amongus font
closes #944
> added m in amongus font

- Fonts/amongus/amongus.h
adding r character in amongus font . . .
closes #994
> adding r character in amongus font . . .

- Fonts/block/block.h
- example.cpp
Added Y to font Block
Reference  #633  
closes #633
> Added Y to font Block

- Fonts/amongus/amongus.h
added f in amongus font
closes #932
> added f in amongus font

- Fonts/amongus/amongus.h
added i in amongus font
closes #934
> added i in amongus font

- Fonts/Boomer/boomer.h
added character w in boomer
closes #1019
> added character w in boomer

- Fonts/drpepper/drpepper.h
Added 'z' character  to dr pepper
closes #871
> Added 'z' character to dr. pepper

- Fonts/amongus/amongus.h
- example.cpp
- readme.md
added letter t : amongus
#1055
> added letter t : amongus

- Fonts/drpepper/drpepper.h
- example.cpp
- readme.md
> added r to font drpapper

- Fonts/drpepper/drpepper.h
- readme.md
> feat: p character

- Fonts/drpepper/drpepper.h
- example.cpp
- readme.md
> added the letter k to the font drpepper

- Fonts/carlos/carlos.h
- example.cpp
- readme.md
> ADDED LETTER 3 : CARLOS

- Fonts/drpepper/drpepper.h
- example.cpp
character 5 added to drpepper
closes #1061
> 5 added to the drpepper

- Fonts/amongus/amongus.h
- readme.md
Added letter 'u' in amongus
closes #1067
> Added letter 'u' in amongus.h

- Fonts/drpepper/drpepper.h
- example.cpp
> W added to drpepper

- Fonts/amongus/amongus.h
- readme.md
Added the letter 'v' in amongus.h
closes #1068
> Added the letter 'v' in amongus.h

- Fonts/Straight/straight.h
Added letter m to font straight. pls add the hactoberfest accepted tag :)
Thank you!
closes #1073
> Add m to straight

- Fonts/amongus/amongus.h
- readme.md
Added the letter 'w' in amongus.h
closes #1069
> Added the letter 'w' in amongus.h

- Fonts/carlos/carlos.h
Added the digit '4' in carlos.h
closes #1064
> Added the digit '4' in carlos.h

- Fonts/drpepper/drpepper.h
Added G to drpepper font
closes #1075
> Add G to drpepper

- Fonts/amongus/amongus.h
- example.cpp
> g added to amongus

- Fonts/carlos/carlos.h
- readme.md
*Adding small character in carlos*
closes #1104
> adding all smal character in carlos

- CONTRIBUTING.md
Improving the contributions file
> Improving Contributions.md file

- CONTRIBUTING.md
- Documentation/Structure.md
> Documentation

- Fonts/amongus/amongus.h
added 'y' to amongus font
closes #971
> added 'y' to amongus

- Ascii.h
- Fonts/Boomer/boomer.h
- Fonts/SevenStar/sevenstar.h
- Fonts/Straight/straight.h
- Fonts/amongus/amongus.h
- Fonts/banner/banner.h
- Fonts/block/block.h
- Fonts/carlos/carlos.h
- Fonts/drpepper/drpepper.h
- Fonts/fonts.h
- Fonts/small/small.h
- Fonts/starwar/starwar.h
There was memory leaks because memory was not released properly. I changed the two dimensional arrays  with vectors of strings, and the raw pointers with unique_ptr to avoid to release the memory manually. Before the maximum number of characters in a row was 100, after that the program crushed, I adapted to obtain more space when needed.
> Fixed memory leaks and expanded the number of charcaters to print

- Fonts/block/block.h
Added character: \<U\> to font: \<Block\>.
Here is the output:
closes #1120
> Add character: <U> to font: <Block>

- Fonts/block/block.h
Added character: \<g\> to font: \<Block\>.
Here is the output:
closes #1125
> Add character: <g> to font: <Block>

- Fonts/block/block.h
Added character <b> to block
here is the output of <b> to block
closes #1122
> Add `<b>` Block

- Fonts/drpepper/drpepper.h
Added character: \<O\> to font: \<drpepper\>.
closes #1023
> Add character: <O> to font: <drpepper>

- Ascii.h
- Fonts/fonts.h
*After printing a sentence i clear the letters matrix and reset the column pointer to zero .*
*OUTPUT*
closes #1129
> bug-fix\clear-matrix

- Fonts/starwar/starwar.h
added character \<S\> to font \<STARWAR\>
closes https://github.com/codewithnick/ascii-art/issues/650
> added character <S> to font <STARWAR>

- Fonts/block/block.h
*feat :  adding character k to font block*
> K to block

- Fonts/block/block.h
> [feature]: adding z to block

- Fonts/block/block.h
-  ## *Feature -> Adding new character x to font block *
- # Screenshot:
- # closes #1173
> [feature:- adding x to block

- Fonts/block/block.h
> [Feature]:-adding w to font block

- Fonts/drpepper/drpepper.h
Added character: \<e\> to font: \<drpepper\>.
Here is the screenshot:
closes #946
> Add character: <e> to font: <drpepper>

- Fonts/block/block.h
Adds lowercase V to font Block
*Screenshot of character*
closes #1163
> [feature]:- adding v to block

- Fonts/block/block.h
- ## *Feature - Adding new character u to font block*
- ### **font block has completed**
closes #1162
> Adding character u to font block

- Fonts/3d-diagonal/3d-diagonal.h
> Adding character  E to 3d-diagonal

- Fonts/3d-diagonal/3d-diagonal.h
*Feature: Add letter Q to 3d-diagonal font*
closes #1219
> Add letter Q to 3d-diagonal font
